#%RAML 1.0
---
title: Practical-Task API
baseUri: localhost:3000/api/
version: v1

/Playlists:
    get:
        getone:
            
        getMany:
    post:
    put:

/Songs:
    /Album:
        get:
            id

/Spotify:
    /Artists:
        /id:
            getone
            getMany

    /Abums:
        /id:
            getOne
            getMany

/Users:
    get:
        displayName: Get User info
        description: Get user by user_id
        headers: 
            Authorization:
                displayName: Authorization
                description: JWT token for Spotify Authorization
                type: string
                required: true
            Content-Type:
                displayName: Content-Type
                description: json data

